# Generated by Django 5.2.7 on 2025-10-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPeaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
