# Generated by Django 5.2.7 on 2025-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPeaApp', '0002_testimonials_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='reviewer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
